services:
  postgres:
    image: postgres:16
    container_name: sankhya_tool_db
    restart: always
    environment:
      POSTGRES_DB: sankhya_tool
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  pied-interactive:
    build: .
    container_name: pied_interactive
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/sankhya_tool
      SANKHYA_SERVICE_URL: http://host.docker.internal:3030

volumes:
  postgres_data:
